site:
  title: Cool Software Documentation
  url: https://abccompany.com/
  start_page: usermanual::index.adoc
content:
  sources:
    - url: ./
      branches: [HEAD]
      start_path: UserManual/
    # - url: https://github.com/cho-uc/AntoraExample.git
    #   branches: [HEAD, branch-v1.0.0, branch-v2.0.0]
    #   start_path: OtherDoc/
output:
  clean: true
  dir: public
antora:
  extensions:
  - '@antora/pdf-extension'
  - '@antora/lunr-extension'
asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    product-name: CoolSoftware
    project-url: https://abccompany.com/
    bib: bibliography#
    experimental: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
